import type { Metadata } from "next";
import "../styles/globals.css";
import { lora, montserrat } from "@/public/assets/font";
import Navbar from "@/components/Navbar";
export const metadata: Metadata = {
  title: "Jaga Jiwa",
  description: "Generated by Jaga Jiwa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${montserrat.variable} mx-auto max-w-2xl antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
